name: "Construção do artefato"

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: victordias21/projeto_go:latest,victordias21/projeto_go:${{ github.sha }}